Speedups and new vdnf
TomClabault/HIPRT-Path-Tracer pull request #11
Opened 2024-11-03 20:48 UTC by tigrazone

2024-11-03 20:57 UTC, tigrazone commented
Also I chsnged ONB calculations to more precise. Read code please

2024-11-04 06:35 UTC, TomClabault requested changes

2024-11-04 06:35 UTC, TomClabault commented on src/HostDeviceCommon/Math.h
> +	inline bool isZERO(float x) { return (x < NEARzero) && (x > -NEARzero); }
Please rename `isZERO` to `is_zero()` for naming consistency. Also `NEARzero` --> `NEAR_ZERO`

2024-11-04 06:35 UTC, TomClabault commented on src/Device/includes/ONB.h
> +      T = make_float3(0.0F, -1.0F, 0.0F);
Same here

2024-11-04 06:35 UTC, TomClabault commented on src/Device/includes/ONB.h
> +    if(N.z < -0.99998796F)  // Handle the singularity
`-1.0F` --> `-1.0f` with a lowercase F for consistency in the codebase.

2024-11-04 06:35 UTC, TomClabault commented on src/Device/includes/ONB.h
> +    {
Omit brackets with a single line in the if block

2024-11-04 06:35 UTC, TomClabault commented on src/HostDeviceCommon/KernelOptions.h
> +//#define GGXAnisotropicSampleFunction GGX_VNDF_SAMPLING
I think you can remove the commented lines here

2024-11-04 06:35 UTC, TomClabault commented on src/HostDeviceCommon/KernelOptions.h
> +//#define GGXAnisotropicSampleFunction GGX_VNDF_BOUNDED
And here

2024-11-04 06:35 UTC, TomClabault commented on src/Device/includes/Sampling.h
> +HIPRT_HOST_DEVICE HIPRT_INLINE float3 GGX_VNDF_bounded_sample(const float3 local_view_direction, float alpha_x, float alpha_y, Xorshift32Generator& random_number_generator)
The overall implementation of the sampling function looks quite different from the reference which makes it harder to understand and follow.

I suppose this is all in the name of performance but in the grand scheme of things, simplifying a few float ops in a sampling function isn't worth it compared to the introduced divergence of the code from the reference in the paper.

I'd prefer an implementation closer to the one presented in the paper.

2024-11-04 06:41 UTC, TomClabault commented
Your implementation is also omitting the PDF (probability distribution function) change required for bounded VNDF sampling as presented in Listing 2 of [[Bounded VNDF Sampling for Smith–GGX Reflections]](https://gpuopen.com/download/publications/Bounded_VNDF_Sampling_for_Smith-GGX_Reflections.pdf).

This PDF change should be adapted in `disney_metallic_eval()`: https://github.com/TomClabault/HIPRT-Path-Tracer/blob/main/src/Device/includes/Disney.h#L102

2024-11-04 06:42 UTC, tigrazone commented on src/HostDeviceCommon/KernelOptions.h
> +//#define GGXAnisotropicSampleFunction GGX_VNDF_SAMPLING
Commented for fast switch

2024-11-04 06:43 UTC, closed without merging